# Generated by Django 4.2.24 on 2025-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('field_mappings', models.JSONField(blank=True, default=dict)),
                ('preview_data', models.JSONField(blank=True, default=list)),
                ('processed_data', models.JSONField(blank=True, default=list)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
