# Generated by Django 4.2.24 on 2025-09-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Street address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('zip_code', models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('sku', models.CharField(help_text='Stock keeping unit', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('quantity', models.IntegerField(default=0, help_text='Available quantity')),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is product active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
