# Generated by Django 4.2.24 on 2025-09-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_company_dynamictestmodel_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicTestModel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
