# Generated by Django 4.2.24 on 2025-09-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_delete_dynamictestmodel_remove_employee_company_and_more'),
    ]

    operations = [
    ]
